language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
services:
  - docker  
before_install:
- docker pull fusionauth/fusionauth-app
install:
  - composer install
script:
  - vendor/bin/phpunit --bootstrap vendor/autoload.php tests/DiscoveryTest
